image: docker:latest
services:
  - docker:dind
  - mysql:latest

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MYSQL_DATABASE: atom
  MYSQL_ROOT_PASSWORD: atom
  MYSQL_USER: atom
  MYSQL_PASSWORD: atom

stages:
  - testing
  - build

test unit:
  image: gradle:jdk-alpine
  stage: testing
  script:
    - mkdir -p .ci_status
    - cd web_hackaton
    - ./wait-for mysql:3306 -- ./gradlew check
    - cd ../
    - echo "test unit"
    - touch .ci_status/test_unit
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  artifacts:
    paths:
      - .ci_status/


docker-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f web_hackaton/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push "$CI_REGISTRY_IMAGE"
    - mkdir -p .ci_status
    - echo "Build"
    - touch .ci_status/build_success    
  artifacts:
    paths:
      - .ci_status/
