stages:
  - testing
  - build

test unit:
  image: gradle:jdk-alpine
  services:
    - mysql:5.5
  stage: testing
  variables:
    MYSQL_DATABASE: atom
    MYSQL_ROOT_PASSWORD: atom
    MYSQL_USER: atom
    MYSQL_PASSWORD: atom
  script:
    - mkdir -p .ci_status
    - web_hackaton/gradlew clean build
    - echo "test unit"
    - touch .ci_status/test_unit
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  artifacts:
    paths:
      - .ci_status/
  artifacts:
    when: on_failure
    paths:
      - web_hackaton/build/reports/tests/test/
      - web_hackaton/build/reports/checkstyle/


docker-build:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay
    SPRING_PROFILES_ACTIVE: gitlab-ci
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f web_hackaton/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE"
    - mkdir -p .ci_status
    - echo "Build"
    - touch .ci_status/build_success    
  artifacts:
    paths:
      - .ci_status/
